name: ergo
description: A scalable, offline-first mobile learning application

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Routing
  go_router: ^12.1.1
  
  # State Management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  
  # Database
  sqflite: ^2.3.0
  path: ^1.8.3
  path_provider: ^2.1.1
  
  # Utilities
  uuid: ^4.2.2
  http: ^1.2.0
  confetti: ^0.8.0
  google_fonts: ^8.0.2
  audioplayers: ^6.5.1
  sqflite_common_ffi: ^2.4.0+2
  flutter_heatmap_calendar: ^1.0.5
  fl_chart: ^1.1.1
  url_launcher: ^6.2.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.5.4
  riverpod_generator: ^2.3.9
  mocktail: ^1.0.4
  flutter_launcher_icons: ^0.14.3
  
flutter:
  uses-material-design: true
  assets:
    - assets/audio/
    - assets/images/app-logo.png
    - assets/images/home-screen.png

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/app-logo.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/images/app-logo.png"
